### ISSUE TITLE
chapter 2 bin/test run two yields the following stack traces..

### ISSUE THREAD

**Issue by bdbaddog** [collective/tutorial.todoapp#1]
After doing:
$ git branch --track chapter2 origin/chapter2  # tell git what chapter2 is
$ git checkout chapter2 src/tutorial/todoapp/tests  # get tests
bin/test yields the following..
Is that expected?

``` python
Williams-MacBook:tutorial.todoapp bdbaddog$ bin/test
Running tutorial.todoapp.tests.base.TodoAppLayer:Integration tests:
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.z2.Startup in 1.081 seconds.
  Set up plone.app.testing.layers.PloneFixture in 40.032 seconds.
  Set up tutorial.todoapp.tests.base.TodoAppLayer/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/fields.py:417: UserWarning: You did not specify an i18n translation domain for the 'description' field in /Users/bdbaddog/devel/plone/tutorial.todoapp/src/tutorial/todoapp/configure.zcml
  "'%s' field in %s" % (self.getName(), context.info.file )
/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/fields.py:417: UserWarning: You did not specify an i18n translation domain for the 'title' field in /Users/bdbaddog/devel/plone/tutorial.todoapp/src/tutorial/todoapp/configure.zcml
  "'%s' field in %s" % (self.getName(), context.info.file )
 Traceback (most recent call last):
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/zope.testing-3.9.7-py2.7.egg/zope/testing/testrunner/runner.py", line 366, in run_layer
    setup_layer(options, layer, setup_layers)
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/zope.testing-3.9.7-py2.7.egg/zope/testing/testrunner/runner.py", line 628, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/zope.testing-3.9.7-py2.7.egg/zope/testing/testrunner/runner.py", line 633, in setup_layer
    layer.setUp()
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/plone.app.testing-4.2-py2.7.egg/plone/app/testing/helpers.py", line 339, in setUp
    self.setUpZope(portal.getPhysicalRoot(), configurationContext)
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/src/tutorial/todoapp/tests/base.py", line 27, in setUpZope
    self.loadZCML(package=tutorial.todoapp)
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/plone.app.testing-4.2-py2.7.egg/plone/app/testing/helpers.py", line 393, in loadZCML
    return xmlconfig.file(name, **kw)
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 651, in file
    context.execute_actions()
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 626, in execute_actions
    callable(*args, **kw)
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/Products.GenericSetup-1.7.1-py2.7.egg/Products/GenericSetup/registry.py", line 756, in registerProfile
    metadata = ProfileMetadata(path, product=product)()
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/Products.GenericSetup-1.7.1-py2.7.egg/Products/GenericSetup/metadata.py", line 56, in __call__
    return self.parseXML( file.read() )
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/Products.GenericSetup-1.7.1-py2.7.egg/Products/GenericSetup/utils.py", line 175, in parseXML
    dom = parseString(xml)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/minidom.py", line 1930, in parseString
    return expatbuilder.parseString(string)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ConfigurationExecutionError: <class 'xml.parsers.expat.ExpatError'>: mismatched tag: line 6, column 2
  in:
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/src/tutorial/todoapp/configure.zcml", line 22.4-28.10
      <genericsetup:registerProfile
          name="default"
          title="tutorial.todoapp"
          directory="profiles/default"
          description='Extension profile for tutorial.todoapp.'
          provides="Products.GenericSetup.interfaces.EXTENSION"
          />


Tearing down left over layers:
  Tear down plone.app.testing.layers.PloneFixture in 0.331 seconds.
  Tear down plone.testing.z2.Startup
Traceback (most recent call last):
  File "bin/test", line 339, in <module>
    '--test-path', '/Users/bdbaddog/devel/plone/tutorial.todoapp/src',
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/zope.testing-3.9.7-py2.7.egg/zope/testing/testrunner/__init__.py", line 35, in run
    failed = run_internal(defaults, args, script_parts=script_parts)
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/zope.testing-3.9.7-py2.7.egg/zope/testing/testrunner/__init__.py", line 48, in run_internal
    runner.run()
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/zope.testing-3.9.7-py2.7.egg/zope/testing/testrunner/runner.py", line 138, in run
    self.run_tests()
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/zope.testing-3.9.7-py2.7.egg/zope/testing/testrunner/runner.py", line 242, in run_tests
    tear_down_unneeded(self.options, (), setup_layers, True)
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/zope.testing-3.9.7-py2.7.egg/zope/testing/testrunner/runner.py", line 605, in tear_down_unneeded
    l.tearDown()
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/plone.testing-4.0.3-py2.7.egg/plone/testing/z2.py", line 300, in tearDown
    self.tearDownBasicProducts()
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/plone.testing-4.0.3-py2.7.egg/plone/testing/z2.py", line 594, in tearDownBasicProducts
    with zopeApp() as app:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/plone.testing-4.0.3-py2.7.egg/plone/testing/z2.py", line 242, in zopeApp
    app = addRequestContainer(Zope2.app(connection), environ=environ)
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/Zope2-2.13.15-py2.7.egg/Zope2/__init__.py", line 52, in app
    return bobo_application(*args, **kw)
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/Zope2-2.13.15-py2.7.egg/App/ZApplication.py", line 75, in __call__
    return connection.root()[aname]
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/ZODB3-3.10.5-py2.7-macosx-10.8-x86_64.egg/ZODB/Connection.py", line 366, in root
    return RootConvenience(self.get(z64))
  File "/Users/bdbaddog/devel/plone/tutorial.todoapp/eggs/ZODB3-3.10.5-py2.7-macosx-10.8-x86_64.egg/ZODB/Connection.py", line 248, in get
    p, serial = self._storage.load(oid, '')
AttributeError: 'NoneType' object has no attribute 'load'
```

**Comment by bdbaddog** [comment]
Never mind found the issue. I had two open "<dependencies>" instead of one open and one close.
